[package]
name = "lore-cloudflare"
edition = "2024"
version.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true }
ring = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
zerocopy = { workspace = true }
lore-base = { workspace = true }
lore-revision = { workspace = true }
lore-storage = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
rand = { workspace = true }
